### ISSUE TITLE
Interactive dismiss

### ISSUE THREAD

**Issue by weiran** [Backelite/MaryPopin#26]
I'm wondering what you think about allowing the modal to be dismissed with a drag gesture, like Tweetbot's photo modal?

**Comment by nakp** [comment]
It may not be the same, but could you disable the actual interactive dismiss which uses UIScreenEdgeGestureRecognizer?

**Comment by sparga** [comment]
The library does not use `UIScreenEdgeGestureRecognizer` so I am not sure which interactive dismiss you are referring to.
Any chance it would be related to [the interactive dismiss](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UINavigationController_Class/index.html#//apple_ref/occ/instp/UINavigationController/interactivePopGestureRecognizer) of the `UINavigationController` ?

**Comment by nakp** [comment]
Yes, I'm still able to dismiss the modal VC with that gesture, and yes, that is the VC responsible of displaying my modal, otherwise would not overlay all the screen and the child view controller seems to move down just the navigationbar height

**Comment by sparga** [comment]
Yes, I see what you mean. I already experienced some issues with the navigation controller interactive dismiss and the best solution so far was to dismiss the popping in that case.
It is not the best solution but, so far, it is the only way I found to avoid the issues I experienced.
