### ISSUE TITLE
MaryPopin + orientation change

### ISSUE THREAD

**Issue by redcirclegame** [Backelite/MaryPopin#35]
How can update background controller when orientation changes ?

**Comment by yasirmturk** [comment]
orientation methods for `presentingPopinController` are not invoked the popin is presented so controller is not able to switch according to popincontroller's orientation

**Comment by sparga** [comment]
It is not how it is supposed to be. Orientation events are forwarded from the parent controller to the child. Here, the `presentingPopinController` is the parent and the popin controller is the child.
Your `presentingPopinController` should receive orientation events through the usual UIViewController methods and this library only take care of forwarding events from the parent to the popin.

**Comment by yasirmturk** [comment]
this is how the normal `presentViewController` method work .. lets look at a situation:
parent is in portrait and i am presenting a view controller that only supports landspace mode.. now what mary popin does it does not cares and draw the presented view controller in portriat too .. while if i use the default `presentViewController` method it works perfect.. and displays the presented view controller in landscape.. are you getting to the problem?

**Comment by sparga** [comment]
I see what you mean but most of the time, when you present a popin you still see the presenting controller in the background and it would look weird to have a portrait controller in the background and a landscape controller in front presented in a popin.
Sure, you can use this library to present a popin in full screen but it is not its main purpose and using the default `presentViewController`method would be more appropriate to deal with the situation you describe.

**Comment by yasirmturk** [comment]
1. it is not full screen
2. i am using it to make stacks not full screen and it makes
3. i mentioned that parent is not restricted to portrait it supports both orientations so it does not look weird

**Comment by sparga** [comment]
Ok, I get your point now. To achieve what you need, it would require to force the parent controller to update its orientation when presenting the popin. Right now, I don't see a way to programmatically change parent orientation.
I will have to experiment to see if it is possible or maybe you already have some idea about how to do this ?

**Comment by yasirmturk** [comment]
yes currently i can force the orientation change but this is not what native present does PLUS it can just change orientation to the specified one but not the mask that popin controller uses
