### ISSUE TITLE
Arrow like popover

### ISSUE THREAD

**Issue by yasirmturk** [Backelite/MaryPopin#37]
can we add an arrow like `UIPopoverController` ?

**Comment by sparga** [comment]
Well, it is not designed to be used like `UIPopoverController` but you can achieve something similar by using a background with an arrow in it and this method :
 ```objc
- (void)presentPopinController:(UIViewController *)popinController fromRect:(CGRect)rect animated:(BOOL)animated
                    completion:(void(^)(void))completion;
```
Obviously, this won't be as powerful as `UIPopoverController' but for simple use cases, it can do the trick.
