### ISSUE TITLE
Keyboard Issue

### ISSUE THREAD

**Issue by galileoguzman** [Backelite/MaryPopin#44]
When I call for show new Popin with Text Fields or TextView and user begin to type on them, the keyboard appear and the Popin take behavior weird. The popin move to down and some Text Fields end behind the Keyboard and the user experience becomes on a grief situation.
Somebody can help me?

**Comment by sparga** [comment]
By default, the popping view react to keyboard notifications but it seems you it is not what you want. You can try disable this behavior with the `BKTPopinIgnoreKeyboardNotification` option.

**Comment by galileoguzman** [comment]
Thank you very much: `BKTPopinIgnoreKeyboardNotification` was the right optioin for my issue.
